/**
 * Generate the browser bundle from `src/client.js`.
 *
 * A client half is **not** a plain ES module. The shell loads each plugin bundle
 * as a classic script that must register its factory itself:
 *
 * ```js
 * window.__ModuleLoader__.load({ id, factory: (require) => { … return module.exports } })
 * ```
 *
 * and the returned exports must carry a Cordis plugin shape (`apply`, optional
 * `inject`). A bundle that is plain ESM evaluates perfectly and registers
 * nothing, which is worse than failing: the shell reports
 * `loaded without registering "…" via __ModuleLoader__.load` and every other
 * client plugin in the same combo goes with it — the settings panel disappears
 * entirely.
 *
 * So this script wraps the page source in that envelope. The envelope is
 * hand-written rather than produced by a bundler because the page imports
 * nothing: `require` is unused, React comes from the shell's frozen module
 * table, and the only browser APIs used are `document` and `navigator`.
 *
 * Run after every change to `src/client.js`:
 *
 * ```sh
 * node tools/build-client.mjs
 * ```
 *
 * `test/client-bundle.test.js` asserts the generated file exists, registers
 * itself, and matches the current page source, so a stale bundle fails the suite.
 *
 * @module dsh-agency-agents/tools/build-client
 */

import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const SOURCE = resolve(ROOT, 'src/client.js')
const TARGET = resolve(ROOT, 'lib/client.js')

/** The package name the bundle registers under; also its served module id. */
const { name: PACKAGE_NAME } = JSON.parse(await readFile(resolve(ROOT, 'package.json'), 'utf8'))

const source = await readFile(SOURCE, 'utf8')

// The page source is copied verbatim, minus the one module-boundary export: in
// the bundle it is a declaration inside the factory, not an ES export.
const REEXPORT = 'export function registerSettingsPage(ctx) {'
if (!source.includes(REEXPORT)) {
  throw new Error(`build-client: expected "${REEXPORT}" in ${SOURCE}; update the marker if the page changed shape`)
}
const body = source
  .replace(REEXPORT, 'function registerSettingsPage(ctx) {')
  .replace('export const CLIENT_SQUADS = SQUADS', 'const CLIENT_SQUADS = SQUADS')
if (/^export /m.test(body)) {
  const stray = body.split('\n').find((line) => line.startsWith('export '))
  throw new Error(`build-client: an ES export survived into the bundle (${stray}); a classic script cannot parse it`)
}

const bundle = `/**
 * Generated by tools/build-client.mjs from src/client.js — do not edit.
 *
 * Client plugin bundle: registers this package's factory with the shell's module
 * loader. The page imports nothing, so the factory's \`require\` is unused and the
 * only globals it needs are React (from the shell's frozen module table),
 * \`document\`, and \`navigator\`.
 */
window.__ModuleLoader__.load({
  id: ${JSON.stringify(PACKAGE_NAME)},
  factory: (require) => {
    const module = { exports: {} }
    const exports = module.exports

${body
  .split('\n')
  .map((line) => (line.length === 0 ? '' : `    ${line}`))
  .join('\n')}

    /**
     * The Cordis plugin: the shell calls \`apply\` once and disposes the returned
     * effect on unload, which is what removes the 专家团 page with the plugin.
     */
    const apply = (ctx) => registerSettingsPage(ctx)

    exports.apply = apply
    exports.inject = []
    return module.exports
  },
})
`

await mkdir(dirname(TARGET), { recursive: true })
await writeFile(TARGET, bundle)
process.stdout.write(`build-client: wrote ${TARGET} (${bundle.length} bytes from ${source.length} bytes of page source)\n`)
