/**
 * Generate the browser bundle from `src/client.js`.
 *
 * A client half is **not** a plain ES module. The shell loads each plugin bundle
 * as a classic script that must register its factory itself:
 *
 *     window.__ModuleLoader__.load({ id, factory: (require) => { … return module.exports } })
 *
 * and the returned exports must carry a Cordis plugin shape (`apply`, optional
 * `inject`). A bundle that is plain ESM evaluates perfectly and registers
 * nothing, which is worse than failing: the shell reports
 * `loaded without registering "…" via __ModuleLoader__.load` and every other
 * client plugin in the same combo goes with it — the settings panel disappears
 * entirely.
 *
 * Two more contracts this envelope satisfies, each learned from a live failure:
 *
 * - **React comes from the module table.** The factory resolves it with
 *   `require("react")`; the runner injects `React` only into a *dynamic* half's
 *   scope, so reading it as a global inside a packaged bundle throws.
 * - **There is no `host.call` here either.** The Package-private RPC belongs to
 *   the dynamic runner; a packaged client half would need a host-registered
 *   remote service. The page therefore carries its own data, which this script
 *   inlines from the vendored corpus at build time.
 *
 * The envelope is hand-written rather than produced by a bundler because the
 * page imports nothing but `react`.
 *
 * Run after every change to `src/client.js`:
 *
 *     node tools/build-client.mjs
 *
 * `test/client-bundle.test.js` runs the generated artifact in a sandbox and
 * asserts all of the above, so a stale or malformed bundle fails the suite.
 *
 * @module dsh-agency-agents/tools/build-client
 */

import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { createNodeIO } from '../src/io.js'
import { loadRoster } from '../src/roster.js'
import { settingsPayload } from '../src/settings.js'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const SOURCE = resolve(ROOT, 'src/client.js')
const TARGET = resolve(ROOT, 'lib/client.js')

/** The package name the bundle registers under; also its served module id. */
const { name: PACKAGE_NAME } = JSON.parse(await readFile(resolve(ROOT, 'package.json'), 'utf8'))

// The page's data, read from the same corpus the Host half indexes. Inlining it
// keeps the page self-sufficient: no RPC, no second source of truth at runtime.
const roster = await loadRoster(createNodeIO(), { root: resolve(ROOT, 'data/agency-agents-zh') })
if (roster.size === 0) throw new Error('build-client: the vendored corpus is empty; run tools/vendor.mjs')
const payload = settingsPayload(roster, {
  source: 'builtin',
  catalogMode: 'compact',
  toolNames: { list: 'agency_list', find: 'agency_find', brief: 'agency_brief', run: 'agency_run', team: 'agency_team', playbook: 'agency_playbook' },
})

const source = await readFile(SOURCE, 'utf8')

// The page source is copied verbatim, minus the module-boundary export: inside
// the bundle it is a declaration in the enclosing script, not an ES export.
const REEXPORT = 'export function registerSettingsPage(ctx) {'
if (!source.includes(REEXPORT)) {
  throw new Error(`build-client: expected "${REEXPORT}" in ${SOURCE}; update the marker if the page changed shape`)
}
const body = source
  .replace(REEXPORT, 'function registerSettingsPage(ctx) {')
  .replace('export const CLIENT_SQUADS = SQUADS', 'const CLIENT_SQUADS = SQUADS')
if (/^export /m.test(body)) {
  const stray = body.split('\n').find((line) => line.startsWith('export '))
  throw new Error(`build-client: an ES export survived into the bundle (${stray}); a classic script cannot parse it`)
}

const data = [
  '/**',
  ' * The roster, inlined at build time by tools/build-client.mjs.',
  ' *',
  ` * ${roster.size} roles across ${payload.departments.length} departments, plus the curated`,
  ' * squads. A packaged client half has no Package-private RPC, so the page',
  ' * carries its own data instead of asking the Host for it.',
  ' */',
  `const __AGENCY_ROSTER__ = ${JSON.stringify(payload)}`,
  '',
].join('\n')

const indented = body
  .split('\n')
  .map((line) => (line.length === 0 ? '' : `    ${line}`))
  .join('\n')

const envelope = [
  '/**',
  ' * Generated by tools/build-client.mjs from src/client.js — do not edit.',
  ' *',
  ' * Client plugin bundle: registers this package\'s factory with the shell module',
  ' * loader. React arrives through the factory\'s require (the frozen module table);',
  ' * everything else the page needs is inlined above.',
  ' */',
  'window.__ModuleLoader__.load({',
  `  id: ${JSON.stringify(PACKAGE_NAME)},`,
  '  factory: (require) => {',
  '    const module = { exports: {} }',
  '    const exports = module.exports',
  '    const React = require("react")',
  '',
  indented,
  '',
  '    const apply = (ctx) => registerSettingsPage(ctx)',
  '',
  '    /**',
  '     * `slots` is a hard dependency, not an optional lookup: the shell calls this',
  '     * plugin\'s apply as soon as it loads, which can be before the slot system is',
  '     * mounted, and an apply that runs early silently contributes nothing.',
  '     * Declaring the dependency makes Cordis wait for it — the shipped client',
  '     * packages declare exactly this.',
  '     */',
  '    exports.apply = apply',
  '    exports.inject = ["slots"]',
  '    return module.exports',
  '  },',
  '})',
  '',
].join('\n')

await mkdir(dirname(TARGET), { recursive: true })
await writeFile(TARGET, `${data}${envelope}`)
process.stdout.write(
  `build-client: wrote ${TARGET} (${data.length + envelope.length} bytes: ${source.length} of page source, ${JSON.stringify(payload).length} of inlined roster)\n`,
)
